version: '3.8'

services:
  frontend:
    build:
      context: ./Techdome-frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Techdome-backend/
    ports:
      - "5000:5000"  # Exposing backend on port 3001
    environment:
      - DB=mongodb://mongo:27017/mydb  # MongoDB connection string
    depends_on:
      - mongo  # Updated to depend on the mongo service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Exposing MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:
